server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: vinaylomate
    url: jdbc:postgresql://localhost:5432/fraud
    password: vinay123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'